import { Container,Box } from '@chakra-ui/react'
export default function ContainerExample(){
    return(
        <>
<Container maxW='2xl' bg='blue.600' centerContent>
  <Box padding='4' bg='blue.400' color='black' maxW='md'>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Suspendisse faucibus interdum posuere lorem ipsum dolor. Eu volutpat odio facilisis mauris. Ornare arcu odio ut sem nulla pharetra diam sit amet. Eget egestas purus viverra accumsan in. Blandit volutpat maecenas volutpat blandit aliquam etiam. Egestas sed sed risus pretium quam vulputate. Vivamus at augue eget arcu dictum varius duis at. Ultrices eros in cursus turpis massa tincidunt dui ut. Sodales ut etiam sit amet nisl purus in mollis. Fusce ut placerat orci nulla pellentesque. Mauris pellentesque pulvinar pellentesque habitant. At risus viverra adipiscing at in tellus integer.

Lectus arcu bibendum at varius vel pharetra. Phasellus egestas tellus rutrum tellus pellentesque. Enim ut tellus elementum sagittis vitae et leo duis. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Sed velit dignissim sodales ut eu sem. Enim ut sem viverra aliquet eget sit. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Vel eros donec ac odio tempor orci dapibus. Venenatis a condimentum vitae sapien. Magna ac placerat vestibulum lectus. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse.

Ac ut consequat semper viverra nam libero justo. Sed faucibus turpis in eu mi bibendum neque egestas. Id diam maecenas ultricies mi eget. Nam libero justo laoreet sit amet cursus. Netus et malesuada fames ac turpis egestas integer. Lorem donec massa sapien faucibus et molestie ac feugiat sed. Viverra adipiscing at in tellus integer feugiat. Eu turpis egestas pretium aenean pharetra. Sem viverra aliquet eget sit amet tellus cras. Elit ullamcorper dignissim cras tincidunt lobortis. Sed velit dignissim sodales ut eu sem integer vitae. Velit laoreet id donec ultrices. Ac felis donec et odio pellentesque diam volutpat commodo.

Pretium quam vulputate dignissim suspendisse in est ante. Pharetra convallis posuere morbi leo. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Volutpat est velit egestas dui id. Purus faucibus ornare suspendisse sed nisi lacus. In nulla posuere sollicitudin aliquam ultrices sagittis. Adipiscing diam donec adipiscing tristique risus. Elementum eu facilisis sed odio morbi quis commodo odio. Arcu ac tortor dignissim convallis aenean. Vitae justo eget magna fermentum. Semper viverra nam libero justo laoreet. Tincidunt augue interdum velit euismod in pellentesque massa. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aliquam malesuada bibendum arcu vitae elementum. Senectus et netus et malesuada fames. Nisl purus in mollis nunc sed. Amet purus gravida quis blandit turpis cursus. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar.

Turpis tincidunt id aliquet risus feugiat in ante metus. Egestas pretium aenean pharetra magna. Quis enim lobortis scelerisque fermentum dui. Ornare suspendisse sed nisi lacus sed viverra. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Sodales neque sodales ut etiam sit amet nisl. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Quis imperdiet massa tincidunt nunc. Ultrices mi tempus imperdiet nulla malesuada. Mi proin sed libero enim sed. Bibendum at varius vel pharetra. Tortor aliquam nulla facilisi cras fermentum odio. Elit eget gravida cum sociis.

A iaculis at erat pellentesque adipiscing. Risus pretium quam vulputate dignissim. Erat pellentesque adipiscing commodo elit. Donec ultrices tincidunt arcu non sodales neque sodales ut. Ultricies integer quis auctor elit sed vulputate mi sit. Et malesuada fames ac turpis egestas sed. Et netus et malesuada fames ac turpis egestas integer eget. Urna condimentum mattis pellentesque id nibh tortor id aliquet. Lacus vel facilisis volutpat est velit egestas dui id. Tortor at risus viverra adipiscing at in tellus integer feugiat. Erat velit scelerisque in dictum non consectetur a erat nam. Laoreet sit amet cursus sit amet dictum sit. Consectetur purus ut faucibus pulvinar elementum integer enim. Feugiat vivamus at augue eget arcu. Potenti nullam ac tortor vitae purus.

Donec ac odio tempor orci dapibus ultrices in iaculis. Quis vel eros donec ac odio tempor orci dapibus. Libero justo laoreet sit amet cursus. Sed velit dignissim sodales ut eu sem integer vitae. Aliquet porttitor lacus luctus accumsan. Sagittis id consectetur purus ut faucibus pulvinar elementum. Elementum sagittis vitae et leo. Auctor eu augue ut lectus. Etiam erat velit scelerisque in dictum non consectetur. Sed id semper risus in hendrerit gravida rutrum quisque. Nunc id cursus metus aliquam.

Nibh ipsum consequat nisl vel pretium lectus quam id. Lacus sed viverra tellus in. Volutpat maecenas volutpat blandit aliquam. Tortor at auctor urna nunc. Magna ac placerat vestibulum lectus. Lorem sed risus ultricies tristique nulla aliquet enim. Integer feugiat scelerisque varius morbi enim nunc. Arcu non odio euismod lacinia. Risus feugiat in ante metus dictum at tempor commodo ullamcorper. In pellentesque massa placerat duis ultricies lacus. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Eu facilisis sed odio morbi quis commodo. Eget gravida cum sociis natoque penatibus.

Sodales ut etiam sit amet nisl. Tellus mauris a diam maecenas sed enim ut sem. Pharetra et ultrices neque ornare aenean. Gravida rutrum quisque non tellus orci ac. Enim eu turpis egestas pretium. Arcu dui vivamus arcu felis. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Tellus in hac habitasse platea. Eget dolor morbi non arcu risus quis varius quam quisque. Nunc non blandit massa enim. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Euismod quis viverra nibh cras pulvinar mattis nunc. Luctus accumsan tortor posuere ac ut consequat. Tellus pellentesque eu tincidunt tortor aliquam. Amet risus nullam eget felis eget nunc lobortis mattis. Volutpat lacus laoreet non curabitur gravida. Varius sit amet mattis vulputate enim nulla aliquet. Morbi non arcu risus quis varius. Euismod elementum nisi quis eleifend quam adipiscing vitae.

Nunc eget lorem dolor sed. Vel eros donec ac odio tempor. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Sed nisi lacus sed viverra tellus. Id ornare arcu odio ut sem nulla. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Pellentesque massa placerat duis ultricies lacus sed turpis. Augue mauris augue neque gravida in fermentum. Ultrices sagittis orci a scelerisque purus semper eget duis. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Sit amet nisl purus in mollis nunc sed id semper. Mattis enim ut tellus elementum sagittis vitae. A diam sollicitudin tempor id eu nisl nunc. Lacus vestibulum sed arcu non odio euismod lacinia at. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Fusce ut placerat orci nulla pellentesque dignissim enim. Placerat vestibulum lectus mauris ultrices eros. Semper quis lectus nulla at volutpat diam ut venenatis.
  {/* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. */}
  </Box>
</Container>
        </>
    )
}